apiVersion: apps/v1
kind: Deployment
metadata:
  name: storesales
  labels:
    app: storesales
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storesales
  template:
    metadata:
      labels:
        app: storesales
    spec:
      containers:
        - name: storesales
          image: username/storesales:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5